name: Gralde check

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build
        run: |
          ./gradlew :app:assembleRelease
      - name: lsd
        run: ls -R app/build/outputs/
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: release.apk
          path: app/build/outputs/apk/release
